[package]
name = "rt-systemd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
futures-util = "0.3.31"
tokio = { version = "1.42.0", features = ["full"] }
zbus = "5.2.0"
